### ISSUE TITLE
Decoding samples captured via microphone

### ISSUE THREAD

**Issue by r-ba** [ggerganov/ggwave-spm#3]
I'm interested in using ggwave to decode samples captured from an iPhone mic (using something like [AVAudioSession](https://developer.apple.com/documentation/avfaudio/avaudiosession)), in similar fashion to your [Waver demo](https://apps.apple.com/us/app/waver-data-over-sound/id1543607865), and was hoping that you might be able to point me in the right direction.

Are there any guidelines I should follow, pitfalls to avoid, or general advice you may have? 

Thanks in advance.

**Comment by ggerganov** [comment]
The most important thing is that by default `ggwave` expects the input audio to be with sample rate of 48000 Hz.
If your captured audio is not sampled at 48 kHz, you have 2 options:
- resample it somehow yourself to 48 kHz
- use `ggwave`'s build-in resampler

The second option has the disadvantage that the built-in resampling that I implemented is not very efficient and uses a lot of CPU. So it might not be suitable for mobile devices.

To use `ggwave`'s build-in resampler, all you have to do is provide the sample rate of your audio in the `parameters` structure.
For example, if your audio is sampled at 44kHz, you simply do:

```swift
var parameters = ggwave_getDefaultParameters()

parameters.sampleFormatInp = GGWAVE_SAMPLE_FORMAT_I16
parameters.sampleFormatOut = GGWAVE_SAMPLE_FORMAT_I16
parameters.sampleRateInp = 44000; // <--- whatever is your sampling rate

let instance = ggwave_init(parameters)
```

All of the above applies also for the playback - i.e. if your output is not at 48kHz, you need to resample the result from `ggwave_encode` or use the built-in resampler via `parameters.sampleRateOut`.

Other than that, the steps in the provided example are all you need to do:
- `ggwave_encode` gives you a PCM that you need to playback somehow in order to send a message
- keep feeding captured audio to `ggwave_decode` to receive audio messages. I usually capture the audio in chunks of 1024 samples and immediately feed it to `ggwave_decode`

It would be awesome to finally get a simple iOS program that can be used as a starting point for other iOS applications.
Definitely let me know if you mange to make progress.

For Android, we already have a [contribution](https://gitlab.com/commonsguy/ggweb-spike) that demonstrates how to use `ggwave` inside a `WebView` in an app. It's not the best way, but it's a starting point and it works pretty good.

**Comment by r-ba** [comment]
I appreciate the help! Ended up being able to decode samples captured from the mic, but for some reason the detection seems less robust than the demo Waver iOS app. So I'm probably doing something wrong still. Will post a code snippet here in the near future.

**Comment by ggerganov** [comment]
@r-ba If you are still interested, I just implemented a basic iOS example using ggwave:

https://github.com/ggerganov/ggwave-objc

**Comment by r-ba** [comment]
@ggerganov Great! Thanks for this.
